### ISSUE TITLE
指令错误

### ISSUE THREAD

**Issue by lin6953** [cubstaryow/nonebot-plugin-HelpWithPic#1]
![image](https://github.com/cubstaryow/nonebot-plugin-HelpWithPic/assets/107689301/54f4d7b0-52e3-4ade-a006-eb9f5756a26d)

**Comment by cubstaryow** [comment]
懂了，下个版本修复

**Comment by cubstaryow** [comment]
哦，你这个，我的本意是用换行来分割参数的，而不是\n这个字符，因为\n代表换行，我现在添加参数分割的设置了。
