### ISSUE TITLE
hwp_main文件中matcher匹配问题

### ISSUE THREAD

**Issue by Adsicmes** [cubstaryow/nonebot-plugin-HelpWithPic#3]
希望能统一命令前缀 使用nonebot的COMMAND_START

help指令使用on_regex所以没有什么问题，使用 `[HWP_COMMANDSTART]help` 就能触发

但是其余两个matcher使用的是on_command，这就导致需要发送
`[COMMAND_START][HWP_COMMANDSTART]helpadd` 和 `[COMMAND_START][HWP_COMMANDSTART]helpdel` 才能触发

**Comment by cubstaryow** [comment]
那我到时候换成regex嗯

**Comment by cubstaryow** [comment]
√
